version: "3.9"

services:
  legends_three:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: legends_three
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/legends_three
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: 016998dad6c68fea05b9df7f6f56fb96
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: legends_three
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
