CREATE TABLE matchs (
  id VARCHAR(36) PRIMARY KEY,
  playerOneID VARCHAR(36) NOT NULL,
  playerTwoID VARCHAR(36) NULL,
  playerWin VARCHAR(36) NULL,
  FOREIGN KEY (playerOneID) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (playerTwoID) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (playerWin) REFERENCES users(id) ON DELETE CASCADE
);
