CREATE TABLE matchs (
  id VARCHAR(36) PRIMARY KEY,
  player1_id VARCHAR(36) NOT NULL,
  player2_id VARCHAR(36) NULL,
  player_win VARCHAR(36) NULL,
  FOREIGN KEY (player1_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (player2_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (player_win) REFERENCES users(id) ON DELETE CASCADE
);
