INSERT INTO system_cards (name, element, phase, attack, life, defense, rarity, description)
VALUES
    -- COMMON
    ('Soldado da Tribo da Água', 'WATER', 'YOUNG', 50, 55, 45, 'COMMON',
     'Um soldado iniciante da tribo da água, treinando técnicas básicas de dobra de água e táticas de combate, sempre pronto para proteger sua aldeia.'),
    ('Soldado da Nação do Fogo', 'FIRE', 'YOUNG', 55, 50, 40, 'COMMON',
     'Um jovem soldado da Nação do Fogo, que busca aprimorar sua habilidade de manipular chamas e seguir os ensinamentos dos mestres da sua terra.'),
    ('Camponês da Terra', 'EARTH', 'YOUNG', 45, 60, 50, 'COMMON',
     'Um simples camponês da terra que descobriu potencial na dobra de terra, usando força e resistência para sobreviver e proteger sua comunidade.'),
    ('Monge do Ar', 'AIR', 'YOUNG', 52, 52, 48, 'COMMON',
     'Monge da Nação do Ar, jovem e ágil, treinando a arte da mobilidade e evasão através do domínio do vento.'),
    ('Aprendiz de Água', 'WATER', 'YOUNG', 55, 53, 47, 'COMMON',
     'Aprendiz de dobra de água dedicado, estudando as técnicas da tribo da água e buscando equilíbrio entre ataque e defesa.'),
    ('Aprendiz de Fogo', 'FIRE', 'YOUNG', 60, 45, 40, 'COMMON',
     'Jovem aprendiz da Nação do Fogo, determinado a dominar chamas e desenvolver habilidades estratégicas para combate.'),
    ('Aprendiz de Terra', 'EARTH', 'YOUNG', 53, 55, 52, 'COMMON',
     'Aprendiz da dobra de terra, treinando resistência e força física, sempre focado em controlar o terreno a seu favor.'),
    ('Aprendiz de Ar', 'AIR', 'YOUNG', 52, 52, 48, 'COMMON',
     'Jovem aprendiz da Nação do Ar, ágil e atento, aprendendo técnicas de evasão e combate com leveza e rapidez.'),
    ('Soldado da Terra', 'EARTH', 'YOUNG', 54, 54, 50, 'COMMON',
     'Soldado da nação da terra, em treinamento, com grande resistência e disciplina, preparado para batalhas defensivas.'),
    ('Caçador da Água', 'WATER', 'YOUNG', 53, 50, 45, 'COMMON',
     'Caçador habilidoso da tribo da água, capaz de rastrear inimigos e usar água estrategicamente em combates.'),
    ('Guerreiro da Água', 'WATER', 'YOUNG', 50, 52, 48, 'COMMON',
     'Guerreiro jovem da tribo da água, rápido e estratégico, combinando ataques diretos com movimentos defensivos.'),
    ('Aprendiz de Fogo II', 'FIRE', 'YOUNG', 52, 54, 46, 'COMMON',
     'Aprendiz de fogo em fase intermediária, desenvolvendo controle sobre chamas e técnicas ofensivas precisas.'),
    ('Guardião da Terra', 'EARTH', 'YOUNG', 50, 53, 52, 'COMMON',
     'Defensor jovem da nação da terra, usando força e disciplina para proteger aliados e manter a linha de frente.'),
    ('Acrobata do Ar', 'AIR', 'YOUNG', 54, 45, 42, 'COMMON',
     'Acrobata ágil da Nação do Ar, mestre em saltos e esquivas, capaz de atacar de ângulos inesperados.'),

    -- RARE
    ('Aang Jovem', 'AIR', 'YOUNG', 70, 60, 55, 'RARE',
     'Aang jovem, prodígio da Nação do Ar, rápido e engenhoso, dominando técnicas básicas de dobra do ar e buscando equilíbrio no mundo.'),
    ('Katara Adulta', 'WATER', 'ADULT', 75, 75, 65, 'RARE',
     'Katara adulta, mestre na dobra de água, habilidosa em curar aliados e controlar a batalha com ataques precisos e estratégicos.'),
    ('Zuko Adulto', 'FIRE', 'ADULT', 80, 75, 70, 'RARE',
     'Zuko adulto, príncipe da Nação do Fogo, que domina o fogo com técnica refinada, buscando justiça e equilíbrio.'),
    ('Toph Metal', 'METAL', 'ADULT', 75, 80, 75, 'RARE',
     'Toph, especialista em dobra de metal, capaz de sentir vibrações no ambiente e transformar qualquer campo em vantagem estratégica.'),
    ('Azula Jovem', 'FIRE', 'YOUNG', 80, 65, 60, 'RARE',
     'Azula jovem, extremamente habilidosa e calculista, usa fogo azul e técnicas de combate com precisão mortal.'),
    ('Korra Jovem', 'WATER', 'YOUNG', 75, 70, 65, 'RARE',
     'Korra jovem, Avatar promissora, poderosa na dobra de todos os elementos e sempre em busca de superar limites.'),
    ('Kuvira', 'METAL', 'ADULT', 75, 85, 80, 'RARE',
     'Kuvira, estrategista da terra, habilidosa em controle militar e mestre da dobra de metal, implacável em batalha.'),

    -- EPIC
    ('Aang Adulto', 'AIR', 'ADULT', 100, 95, 85, 'EPIC',
     'Aang adulto, Avatar completo, mestre das artes do ar, rápido, estratégico e capaz de equilibrar ataque e defesa com maestria.'),
    ('Katara Dobra de Sangue', 'BLOOD', 'MASTER', 110, 90, 80, 'EPIC',
     'Katara, mestre da dobra de sangue, poderosa e precisa, capaz de controlar adversários diretamente usando sua técnica proibida.'),
    ('Iroh Mestre', 'FIRE', 'MASTER', 105, 115, 100, 'EPIC',
     'Iroh, sábio e mestre da dobra de fogo, combina experiência e inteligência para proteger aliados e derrotar inimigos com estratégia.'),
    ('Azula Adulto', 'FIRE', 'ADULT', 115, 95, 85, 'EPIC',
     'Azula adulta, dominando fogo azul, extremamente letal e imprevisível, capaz de manipular a batalha com superioridade.'),
    ('Korra Adulto', 'AVATAR', 'ADULT', 110, 105, 95, 'EPIC',
     'Korra adulta, Avatar poderosa, equilibrada e experiente, capaz de controlar todos os elementos e liderar com autoridade.'),
    ('Zaheer', 'AIR', 'ADULT', 105, 95, 85, 'EPIC',
     'Zaheer, mestre do ar e combatente estratégico, usa liberdade e movimento rápido para dominar inimigos em qualquer situação.'),
    ('Hama', 'BLOOD', 'ADULT', 100, 90, 80, 'EPIC',
     'Hama, especialista na dobra de sangue, utiliza técnicas perigosas para controlar adversários e virar o jogo em batalha.'),
    ('Bumi', 'EARTH', 'MASTER', 110, 110, 100, 'EPIC',
     'Bumi, mestre da dobra de terra, estrategista nato, capaz de transformar o terreno em armadilha e surpreender inimigos.'),

    -- LEGENDARY
    ('Aang Avatar Mestre', 'AVATAR', 'MASTER', 150, 150, 130, 'LEGENDARY',
     'Aang no auge de seu poder como Avatar, equilibrando todos os elementos, rápido e letal, símbolo de esperança e justiça.'),
    ('Korra Avatar Mestre', 'AVATAR', 'MASTER', 155, 145, 135, 'LEGENDARY',
     'Korra no auge de suas habilidades como Avatar, capaz de controlar todos os elementos com perfeição, liderança e coragem.'),
    ('Roku', 'AVATAR', 'MASTER', 160, 160, 140, 'LEGENDARY',
     'Avatar Roku, sábio e poderoso, mestre de todos os elementos, que mantém equilíbrio e sabedoria entre as nações.'),
    ('Kyoshi', 'AVATAR', 'MASTER', 170, 165, 150, 'LEGENDARY',
     'Avatar Kyoshi, lendária e formidável, com técnicas de combate únicas e presença imponente em todas as batalhas.'),
    ('Wan', 'AVATAR', 'MASTER', 165, 155, 145, 'LEGENDARY',
     'Avatar Wan, o primeiro Avatar da história, mestre de todos os elementos, estabelecendo o ciclo de equilíbrio entre o mundo e o espírito.');
