CREATE EXTENSION IF NOT EXISTS "pgcrypto";

INSERT INTO cards (id, user_id, name, element, phase, attack, defense, rarity)
VALUES
    (gen_random_uuid(), NULL, 'Soldado da Tribo da Água', 'WATER', 'YOUNG', 22, 25, 'COMMON'),
    (gen_random_uuid(), NULL, 'Soldado da Nação do Fogo', 'FIRE', 'YOUNG', 24, 21, 'COMMON'),
    (gen_random_uuid(), NULL, 'Camponês da Terra', 'EARTH', 'YOUNG', 20, 26, 'COMMON'),
    (gen_random_uuid(), NULL, 'Monge do Ar', 'AIR', 'YOUNG', 21, 22, 'COMMON'),
    (gen_random_uuid(), NULL, 'Aprendiz de Água', 'WATER', 'YOUNG', 25, 23, 'COMMON'),
    (gen_random_uuid(), NULL, 'Aprendiz de Fogo', 'FIRE', 'YOUNG', 26, 20, 'COMMON'),
    (gen_random_uuid(), NULL, 'Aprendiz de Terra', 'EARTH', 'YOUNG', 23, 25, 'COMMON'),
    (gen_random_uuid(), NULL, 'Aprendiz de Ar', 'AIR', 'YOUNG', 22, 22, 'COMMON'),
    (gen_random_uuid(), NULL, 'Soldado da Terra', 'EARTH', 'YOUNG', 24, 24, 'COMMON'),
    (gen_random_uuid(), NULL, 'Caçador da Água', 'WATER', 'YOUNG', 23, 21, 'COMMON'),
    (gen_random_uuid(), NULL, 'Guerreiro da Água', 'WATER', 'YOUNG', 21, 22, 'COMMON'),
    (gen_random_uuid(), NULL, 'Aprendiz de Fogo II', 'FIRE', 'YOUNG', 22, 24, 'COMMON'),
    (gen_random_uuid(), NULL, 'Guardião da Terra', 'EARTH', 'YOUNG', 21, 23, 'COMMON'),
    (gen_random_uuid(), NULL, 'Acrobata do Ar', 'AIR', 'YOUNG', 24, 20, 'COMMON'),
    (gen_random_uuid(), NULL, 'Aang Jovem', 'AIR', 'YOUNG', 7, 5, 'RARE'),
    (gen_random_uuid(), NULL, 'Aang Adulto', 'AIR', 'ADULT', 9, 8, 'EPIC'),
    (gen_random_uuid(), NULL, 'Aang Avatar Mestre', 'AVATAR', 'MASTER', 12, 12, 'LEGENDARY'),
    (gen_random_uuid(), NULL, 'Katara Jovem', 'WATER', 'YOUNG', 6, 6, 'COMMON'),
    (gen_random_uuid(), NULL, 'Katara Adulta', 'WATER', 'ADULT', 9, 9, 'RARE'),
    (gen_random_uuid(), NULL, 'Katara Dobra de Sangue', 'BLOOD', 'MASTER', 11, 8, 'EPIC'),
    (gen_random_uuid(), NULL, 'Zuko Jovem', 'FIRE', 'YOUNG', 7, 5, 'COMMON'),
    (gen_random_uuid(), NULL, 'Zuko Adulto', 'FIRE', 'ADULT', 10, 9, 'RARE'),
    (gen_random_uuid(), NULL, 'Iroh Mestre', 'FIRE', 'MASTER', 11, 12, 'EPIC'),
    (gen_random_uuid(), NULL, 'Toph Jovem', 'EARTH', 'YOUNG', 8, 7, 'COMMON'),
    (gen_random_uuid(), NULL, 'Toph Metal', 'METAL', 'ADULT', 10, 9, 'RARE'),
    (gen_random_uuid(), NULL, 'Azula Jovem', 'FIRE', 'YOUNG', 9, 6, 'RARE'),
    (gen_random_uuid(), NULL, 'Azula Adulto', 'FIRE', 'ADULT', 11, 8, 'EPIC'),
    (gen_random_uuid(), NULL, 'Korra Jovem', 'WATER', 'YOUNG', 8, 7, 'RARE'),
    (gen_random_uuid(), NULL, 'Korra Adulto', 'AVATAR', 'ADULT', 11, 10, 'EPIC'),
    (gen_random_uuid(), NULL, 'Korra Avatar Mestre', 'AVATAR', 'MASTER', 13, 12, 'LEGENDARY'),
    (gen_random_uuid(), NULL, 'Zaheer', 'AIR', 'ADULT', 10, 8, 'EPIC'),
    (gen_random_uuid(), NULL, 'Kuvira', 'METAL', 'ADULT', 9, 10, 'RARE'),
    (gen_random_uuid(), NULL, 'Hama', 'BLOOD', 'ADULT', 9, 7, 'EPIC'),
    (gen_random_uuid(), NULL, 'Bumi', 'EARTH', 'MASTER', 11, 11, 'EPIC'),
    (gen_random_uuid(), NULL, 'Roku', 'AVATAR', 'MASTER', 12, 12, 'LEGENDARY'),
    (gen_random_uuid(), NULL, 'Kyoshi', 'AVATAR', 'MASTER', 14, 13, 'LEGENDARY'),
    (gen_random_uuid(), NULL, 'Mai', 'FIRE', 'YOUNG', 7, 6, 'COMMON'),
    (gen_random_uuid(), NULL, 'Ty Lee', 'AIR', 'YOUNG', 6, 7, 'COMMON'),
    (gen_random_uuid(), NULL, 'Wan', 'AVATAR', 'MASTER', 13, 11, 'LEGENDARY');
